name: Node.js CI/CD

on:
  push:
    branches: [ canary-v0.0.1 ]
  pull_request:
    branches: [ canary-v0.0.1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build # Pastikan script ini mengkompilasi TypeScript ke JavaScript

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/be-astra-bengkel:canary-v0.0.5
          docker push ${{ secrets.DOCKER_USERNAME }}/be-astra-bengkel:canary-v0.0.5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/be-astra-bengkel:canary-v0.0.5
            docker stop be-astra-bengkel || true
            docker rm be-astra-bengkel || true
            docker run -d --name be-astra-bengkel -p 8080:3000 ${{ secrets.DOCKER_USERNAME }}/be-astra-bengkel:canary-v0.0.5
